# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KIpoBfovvAF1zGN2a7iUcGmM47Sh7ecv
"""

from transformers import pipeline

def analisador_de_sentimento(texto):
    sentiment_analysis = pipeline('sentiment-analysis', model='nlptown/bert-base-multilingual-uncased-sentiment')
    result = sentiment_analysis(texto)
    return result[0]

if __name__ == "__main__":
    texto_usuario = input("Insira o texto para análise de sentimento: ")
    resultado = analisador_de_sentimento(texto_usuario)

    print(f"Sentimento: {resultado['label']} com confiança de {resultado['score']:.2f}")
